[Unit]
Wants=cm5-headphone-monitor.service
After=cm5-headphone-monitor.service
[Service]
Environment=ITUNER_CM5_AUDIO=1
Environment=ITUNER_CM5_JACK_STATE=/run/cm5-headphone/state.json
Environment=ALSA_CONFIG_PATH=/etc/ituner-sdr/cm5-audio-alsa.conf
SupplementaryGroups=gpio
ExecStopPost=/usr/bin/pinctrl set 13 op dl
