/* Shared receiver editor. Text from receiver directories is always textContent. */
class DigitalControls {
  constructor(mode, refresh) {
    this.mode=mode; this.refresh=refresh; this.token=''; this.pending=new Set(); this.options=null;
    const style=document.createElement('style');
    style.textContent=`.receiver-toolbar{display:flex;align-items:center;gap:14px;flex-wrap:wrap;margin:16px 0}.receiver-toolbar p{margin:0}.receiver-actions{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}.receiver-editor{box-sizing:border-box;margin:auto;width:660px;max-width:calc(100vw - 28px);max-height:90vh;overflow:auto;padding:24px;background:#0d2029;color:#d9e9ee;border:1px solid #3e6a73;border-radius:12px}.receiver-editor h2{margin:0 0 12px}.receiver-editor label{display:block;margin:16px 0 6px}.receiver-editor input:not([type=checkbox]),.receiver-editor select{width:100%;box-sizing:border-box;font:inherit;background:#15343d;color:#d9e9ee;border:1px solid #3e6a73;border-radius:8px;padding:12px;min-height:46px}.receiver-editor .editor-actions{display:flex;gap:10px;justify-content:flex-end;flex-wrap:wrap;margin-top:24px}.receiver-editor button{float:none}.receiver-editor .danger{margin-right:auto;border-color:#af7171;color:#ffd3cf}.receiver-editor .editor-error{color:#ffcf8b;min-height:1.5em}.receiver-editor small{display:block;overflow-wrap:anywhere;color:#8faeb9}.receiver-editor::backdrop{background:#000b}.receiver-actions button:focus-visible,.receiver-toolbar button:focus-visible{outline:3px solid #68eac2;outline-offset:3px}`;
    document.head.append(style);
    this.bar=document.createElement('div');this.bar.className='receiver-toolbar';
    this.add=document.createElement('button');this.add.textContent='+ Add decoder';this.add.disabled=true;this.add.onclick=()=>this.open();
    const hint=document.createElement('p');hint.textContent='Choose a receiver and band here or on the SDR display.';
    this.bar.append(this.add,hint);document.getElementById('receiver-toolbar').append(this.bar);
    this.editor=document.createElement('dialog');this.editor.className='receiver-editor';
    this.editor.innerHTML=`<form><h2 id="editor-title"></h2><p>Select the KiwiSDR receiver and listening band.</p><label for="receiver-search">Find a receiver</label><input id="receiver-search" type="search" placeholder="Name, location or address" autocomplete="off"><label for="receiver-choice">Receiver</label><select id="receiver-choice" required></select><small id="receiver-address"></small><label for="band-choice">Band / frequency</label><select id="band-choice" required></select><label id="start-label"><input id="start-now" type="checkbox" checked> Start immediately</label><p class="editor-error" role="status" aria-live="polite"></p><div class="editor-actions"><button type="button" class="danger">Remove decoder</button><button type="button" class="cancel">Cancel</button><button type="submit" class="save">Add decoder</button></div></form>`;
    document.body.append(this.editor);this.editor.setAttribute('aria-labelledby','editor-title');
    this.form=this.editor.querySelector('form');this.search=this.editor.querySelector('#receiver-search');this.receiver=this.editor.querySelector('#receiver-choice');this.band=this.editor.querySelector('#band-choice');this.error=this.editor.querySelector('.editor-error');this.save=this.editor.querySelector('.save');this.remove=this.editor.querySelector('.danger');
    this.search.oninput=()=>this.filterReceivers();this.receiver.onchange=()=>this.showAddress();
    this.editor.querySelector('.cancel').onclick=()=>this.editor.close();this.form.onsubmit=e=>{e.preventDefault();this.submit()};
    this.editor.addEventListener('cancel',e=>{if(this.saving)e.preventDefault()});
    this.remove.onclick=async()=>{if(!confirm('Remove this decoder? Its receiver connection will stop. Saved images and log files are kept.'))return;await this.sendEditor('delete')};
  }
  setData(data){this.token=data.control_token||'';this.add.disabled=!this.token;}
  buttons(row){const box=document.createElement('div');box.className='receiver-actions';
    const start=document.createElement('button');start.textContent=this.pending.has(row.id)?'Applying…':row.running?'Stop':'Start';start.disabled=!this.token||this.pending.has(row.id);start.ariaLabel=(row.running?'Stop ':'Start ')+row.name+' '+row.band;
    start.onclick=()=>this.toggle(row,start);
    const edit=document.createElement('button');edit.textContent='Edit receiver / band';edit.disabled=start.disabled;edit.ariaLabel='Edit '+row.name+' '+row.band;edit.onclick=()=>this.open(row);
    box.append(start,edit);return box;
  }
  async request(action,id,config){const response=await fetch('/api/'+this.mode+'/control',{method:'POST',headers:{'Content-Type':'application/json','X-SDR-Control':this.token},body:JSON.stringify({id,action,config})});let data;try{data=await response.json()}catch(e){throw Error('No confirmation from the SDR. Refresh before retrying.')};if(!response.ok)throw Error(data.error||'Could not update decoder');return data;}
  notice(message){document.getElementById('notice').textContent=message;}
  async toggle(row,button){this.pending.add(row.id);button.disabled=true;button.textContent='Applying…';this.notice('');try{await this.request(row.running?'stop':'start',row.id);this.notice(row.name+(row.running?' stopped.':' started.'))}catch(e){this.notice(e.message)}finally{this.pending.delete(row.id);await this.refresh()}}
  async open(row=null){if(this.editor.open)return;this.row=row;const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);this.newId='web-'+Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');this.error.textContent='Loading receivers…';this.search.value='';this.receiver.replaceChildren();this.band.replaceChildren();this.save.disabled=true;this.remove.hidden=!row;this.remove.disabled=true;this.editor.querySelector('#editor-title').textContent=row?'Edit '+this.mode.toUpperCase()+' decoder':'Add '+this.mode.toUpperCase()+' decoder';this.save.textContent=row?'Save changes':'Add decoder';this.editor.querySelector('#start-label').hidden=!!row;this.editor.querySelector('#start-now').checked=true;this.editor.showModal();
    try{const response=await fetch('/api/digital/options',{cache:'no-store'});if(!response.ok)throw Error('Cannot load the receiver list');this.options=await response.json();if(!this.editor.open)return;this.filterReceivers(row?.server);const presets=this.options.presets[this.mode];for(const p of presets)this.band.add(new Option(p.band+(this.mode==='wspr'?' m':'')+' · '+(p.freq_khz/1000).toFixed(4)+' MHz '+p.mode.toUpperCase(),p.id));const chosen=row?presets.find(p=>Number(p.freq_khz)===Number(row.freq_khz)&&(this.mode==='wspr'||p.mode===row.mode)):presets.find(p=>p.band==='20'||p.band==='20 m');if(chosen)this.band.value=chosen.id;this.error.textContent='';this.save.disabled=!this.receiver.value;this.remove.disabled=false;}catch(e){this.error.textContent=e.message}
  }
  filterReceivers(selected){const old=selected||this.receiver.value;const query=this.search.value.trim().toLowerCase();this.receiver.replaceChildren();for(const r of this.options?.receivers||[]){if(query&&!(r.name+' '+r.location+' '+r.server).toLowerCase().includes(query))continue;this.receiver.add(new Option(r.name+(r.location?' · '+r.location:''),r.server))}if([...this.receiver.options].some(o=>o.value===old))this.receiver.value=old;this.save.disabled=!this.receiver.value;this.showAddress()}
  showAddress(){this.editor.querySelector('#receiver-address').textContent=this.receiver.value||'No matching receivers';}
  async submit(){if(!this.form.reportValidity())return;await this.sendEditor(this.row?'edit':'add',{server:this.receiver.value,preset:this.band.value,start:this.editor.querySelector('#start-now').checked})}
  async sendEditor(action,config){if(this.saving)return;this.saving=true;this.error.textContent='Applying…';for(const el of this.form.elements)el.disabled=true;try{await this.request(action,this.row?.id||this.newId,config);this.editor.close();this.notice(action==='delete'?'Decoder removed. Saved images and log files were kept.':action==='edit'?'Receiver and band updated.':'Decoder added.');await this.refresh()}catch(e){this.error.textContent=e.message}finally{this.saving=false;for(const el of this.form.elements)el.disabled=false}}
}
